# Generated by Django 5.2.7 on 2025-11-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalogger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
