# Generated by Django 5.2.7 on 2025-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datalogger", "0002_sensor_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
